### ISSUE TITLE
Can't update 1.1.0

### ISSUE THREAD

**Issue by Blawuken** [Blawuken/Neko_v2rayNG#7]
*Sent by [**pperpepiheo225@gmail.com**](mailto:pperpepiheo225@gmail.com)*

Description:
---

Apk is packaged incorrectly and cannot be updated 

Device info:
---
<table>
<tr><td>App version</td><td>1.0.7</td></tr>
<tr><td>App version code</td><td>2000217</td></tr>
<tr><td>Android build version</td><td>N986USQS3HWB7</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TP1A.220624.014.N986USQS3HWB7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>c2q</td></tr>
<tr><td>Device model</td><td>SM-N986U</td></tr>
<tr><td>Device product name</td><td>c2qsqw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by NiiMewo** [comment]
![Screenshot_20240510_171804_Package installer](https://github.com/Blawuken/Neko_v2rayNG/assets/83754720/f9f68d4c-73c6-448c-ac7f-0a39e4de2182)
Translate the notice : The app hasn't been installed yet because the package appears to be invalid 
I have tried both ARM v7a and ARM64 v8a but it seems I cannot update

**Comment by Blawuken** [comment]
Try uninstalling and installing the latest version
